ARG RUBY_VERSION=3.3.5
FROM public.ecr.aws/docker/library/ruby:$RUBY_VERSION

RUN apt-get update -qq && \
    apt-get install -y build-essential libvips postgresql-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

# Rails app lives here
WORKDIR /rails

ENV RACK_ENV="test" \
    BUNDLE_WITHOUT="production"

# Install application gems
COPY Gemfile Gemfile.lock .ruby-version ./
COPY vendor/cache vendor/cache
RUN bundle install --local

# Copy application code
COPY . .

# Start the server by default, this can be overwritten at runtime
CMD ["./bin/dev"]